# Generated by Django 3.0.7 on 2020-07-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('pic_id', models.IntegerField()),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('pic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic_path', models.CharField(default='#', max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
                ('authorization', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(default='male', max_length=1024)),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('expression', models.CharField(default='smile', max_length=1024)),
                ('face_shape', models.CharField(default='heart', max_length=1024)),
                ('glasses', models.CharField(default='no glass', max_length=1024)),
                ('thumbsUpTime', models.IntegerField(default=0)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
            ],
            options={
                'permissions': (('thumbs_up', 'can give user thumbs up'), ('make_comments', 'can make comments'), ('high_quality_voice', 'can get result with high quality voice'), ('get_top_face', 'can get top 8 of all faces')),
            },
        ),
    ]
